// src/lib/college-data.ts

/**
 * @fileOverview This file contains the master list of Canadian Designated Learning Institutions (DLIs).
 * This data is used by the `findColleges` AI flow as the source of truth for generating recommendations.
 * To update the college information shown to users, edit the array below.
 */

export const collegeData = [
  {
    dliNumber: 'O19395536013',
    name: 'University of Toronto',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 45000,
    tuitionHigh: 60000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic building',
    programs: ['Computer Science', 'Engineering', 'Rotman Commerce', 'Life Sciences'],
  },
  {
    dliNumber: 'O19330128543',
    name: 'University of British Columbia',
    province: 'BC',
    city: 'Vancouver',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 40000,
    tuitionHigh: 55000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'modern campus',
    programs: ['Business', 'Sauder School of Business', 'Computer Science', 'Psychology'],
  },
  {
    dliNumber: 'O19359011033',
    name: 'McGill University',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 25000,
    tuitionHigh: 45000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'university campus',
    programs: ['Arts and Science', 'Engineering', 'Medicine', 'Management'],
  },
  {
    dliNumber: 'O19283850632',
    name: 'University of Alberta',
    province: 'AB',
    city: 'Edmonton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 28000,
    tuitionHigh: 40000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'university building',
    programs: ['Engineering', 'Business', 'Pharmacy', 'Education'],
  },
  {
    dliNumber: 'O19394569539',
    name: 'Seneca College',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 22000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'college campus',
    programs: ['Business Administration', 'Computer Programming', 'Animation', 'Fashion Arts'],
  },
  {
    dliNumber: 'O19376104272',
    name: 'Humber College',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 23000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'modern building',
    programs: ['Business Management', 'Web Design and Development', 'Paralegal Studies', 'Baking and Pastry Arts'],
  },
  {
    dliNumber: 'O19330349392',
    name: 'BCIT (British Columbia Institute of Technology)',
    province: 'BC',
    city: 'Burnaby',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 25000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'tech campus',
    programs: ['Computer Systems Technology', 'Architectural and Building Technology', 'Marketing Management', 'Nursing'],
  },
  {
    dliNumber: 'O19273752532',
    name: 'SAIT (Southern Alberta Institute of Technology)',
    province: 'AB',
    city: 'Calgary',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 24000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'city campus',
    programs: ['Petroleum Engineering Technology', 'Journalism', 'Aircraft Maintenance', 'Culinary Arts'],
  },
   {
    dliNumber: 'O19395677334',
    name: 'McMaster University',
    province: 'ON',
    city: 'Hamilton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 35000,
    tuitionHigh: 50000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic campus',
    programs: ['Health Sciences', 'Engineering', 'DeGroote School of Business', 'Humanities'],
  },
  {
    dliNumber: 'O19396228869',
    name: 'University of Waterloo',
    province: 'ON',
    city: 'Waterloo',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 42000,
    tuitionHigh: 58000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'tech university',
    programs: ['Computer Science (Co-op)', 'Software Engineering', 'Mathematics', 'Optometry'],
  },
  {
    dliNumber: 'O19359011043',
    name: 'Concordia University',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 24000,
    tuitionHigh: 38000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'urban campus',
    programs: ['Fine Arts', 'John Molson School of Business', 'Communication Studies', 'Aerospace Engineering'],
  },
  {
    dliNumber: 'O19330235462',
    name: 'Simon Fraser University',
    province: 'BC',
    city: 'Burnaby',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 30000,
    tuitionHigh: 45000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'mountain campus',
    programs: ['Computing Science', 'Beedie School of Business', 'Interactive Arts and Technology', 'Health Sciences'],
  },
  {
    dliNumber: 'O19394931351',
    name: 'George Brown College',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 25000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'downtown college',
    programs: ['Culinary Management', 'Graphic Design', 'Construction Management', 'Early Childhood Education'],
  },
  {
    dliNumber: 'O19358462912',
    name: 'Dawson College',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 8000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'cegep building',
    programs: ['3D Animation', 'Nursing', 'Computer Science Technology', 'Social Service'],
  },
  {
    dliNumber: 'O19273733362',
    name: 'University of Calgary',
    province: 'AB',
    city: 'Calgary',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 25000,
    tuitionHigh: 38000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'university architecture',
    programs: ['Engineering', 'Kinesiology', 'Haskayne School of Business', 'Veterinary Medicine'],
  },
  {
    dliNumber: 'O19395677602',
    name: 'Fanshawe College',
    province: 'ON',
    city: 'London',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'modern college',
    programs: ['Aviation', 'Business', 'IT', 'Health Sciences'],
  },
  {
    dliNumber: 'O18713247882',
    name: 'Dalhousie University',
    province: 'NS',
    city: 'Halifax',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 20000,
    tuitionHigh: 35000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'maritime university',
    programs: ['Oceanography', 'Computer Science', 'Law', 'Dentistry'],
  },
  {
    dliNumber: 'O19330543162',
    name: 'Langara College',
    province: 'BC',
    city: 'Vancouver',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 22000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'community college',
    programs: ['University Transfer', 'Business Administration', 'Nursing', 'Web and Mobile App Design'],
  },
  {
    dliNumber: 'O19395083444',
    name: 'Algonquin College',
    province: 'ON',
    city: 'Ottawa',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 23000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'ottawa campus',
    programs: ['Animation', 'Public Relations', 'Construction Engineering Technician', 'Dental Hygiene'],
  },
  {
    dliNumber: 'O19394931342',
    name: 'Red River College Polytechnic',
    province: 'MB',
    city: 'Winnipeg',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'polytechnic school',
    programs: ['Business Information Technology', 'Creative Communications', 'Civil Engineering Technology', 'Hospitality'],
  },
];
