
/**
 * @fileOverview This file contains the master list of Canadian Designated Learning Institutions (DLIs).
 * This data is used by the `findColleges` AI flow as the source of truth for generating recommendations.
 * To update the college information shown to users, edit the array below.
 * **Sources:** The DLI numbers and campus eligibility information are based on the official IRCC Designated Learning Institution list. Tuition ranges and popular programs are drawn from institutional data and common program offerings as of 2025.
 */

export type College = {
  dliNumber: string;
  name: string;
  province: string;
  city: string;
  pgwpEligible: boolean;
  sdsEligible: boolean;
  tuitionLow: number;
  tuitionHigh: number;
  image: string;
  aiHint: string;
  programs: string[];
};

export const collegeData: College[] = [
  // Ontario
  {
    dliNumber: 'O19332746152',
    name: 'University of Toronto',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 30000,
    tuitionHigh: 60000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic campus',
    programs: ['Computer Science', 'Engineering', 'Business', 'Medicine'],
  },
  {
    dliNumber: 'O19395535729',
    name: 'McMaster University',
    province: 'ON',
    city: 'Hamilton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 28000,
    tuitionHigh: 45000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'modern campus',
    programs: ['Health Sciences', 'Engineering', 'Business', 'Humanities'],
  },
  {
    dliNumber: 'O19305471522',
    name: 'University of Waterloo',
    province: 'ON',
    city: 'Waterloo',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 27000,
    tuitionHigh: 35000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'tech campus',
    programs: ['Computer Science', 'Engineering', 'Mathematics', 'Business'],
  },
  {
    dliNumber: 'O19375892122',
    name: 'Western University',
    province: 'ON',
    city: 'London',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 25000,
    tuitionHigh: 40000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'gothic campus',
    programs: ['Business', 'Medical Sciences', 'Engineering', 'Law'],
  },
  {
    dliNumber: 'O19376023352',
    name: "Queen's University",
    province: 'ON',
    city: 'Kingston',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 27000,
    tuitionHigh: 42000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic campus',
    programs: ['Business', 'Engineering', 'Health Sciences', 'Arts & Science'],
  },
  {
    dliNumber: 'O19361109242',
    name: 'York University',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 25000,
    tuitionHigh: 32000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'urban campus',
    programs: ['Business Administration', 'Engineering', 'Psychology', 'Law'],
  },
  {
    dliNumber: 'O19397188593',
    name: 'University of Ottawa',
    province: 'ON',
    city: 'Ottawa',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 24000,
    tuitionHigh: 35000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'bilingual campus',
    programs: ['Law', 'Medicine', 'Engineering', 'Social Sciences'],
  },
  {
    dliNumber: 'O19332687812',
    name: 'Carleton University',
    province: 'ON',
    city: 'Ottawa',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 23000,
    tuitionHigh: 33000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'riverside campus',
    programs: ['Engineering', 'Public Affairs', 'Journalism', 'Business'],
  },
  {
    dliNumber: 'O19395677651',
    name: 'Toronto Metropolitan University (TMU)',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 24000,
    tuitionHigh: 29000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'downtown campus',
    programs: ['Business Management', 'Engineering', 'Media Arts', 'Computer Science'],
  },
  {
    dliNumber: 'O19305391192',
    name: 'University of Guelph',
    province: 'ON',
    city: 'Guelph',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 24000,
    tuitionHigh: 32000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'green campus',
    programs: ['Biological Sciences', 'Agriculture', 'Veterinary Medicine', 'Business'],
  },
  {
    dliNumber: 'O19395164307',
    name: 'Wilfrid Laurier University',
    province: 'ON',
    city: 'Waterloo',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 22000,
    tuitionHigh: 30000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'urban campus',
    programs: ['Business & Economics', 'Psychology', 'Music', 'Computer Science'],
  },
  {
    dliNumber: 'O19358946722',
    name: 'University of Windsor',
    province: 'ON',
    city: 'Windsor',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 21000,
    tuitionHigh: 29000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'border city campus',
    programs: ['Engineering', 'Law', 'Business', 'Human Kinetics'],
  },
  {
    dliNumber: 'O19394569014',
    name: 'Brock University',
    province: 'ON',
    city: 'St. Catharines',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 21000,
    tuitionHigh: 27000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'vineyard campus',
    programs: ['Business Administration', 'Health Sciences', 'Education', 'Sport Management'],
  },
  {
    dliNumber: 'O19395164223',
    name: 'Trent University',
    province: 'ON',
    city: 'Peterborough',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 20000,
    tuitionHigh: 24000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'riverside campus',
    programs: ['Environmental Science', 'Forensic Science', 'Business', 'Nursing'],
  },
  {
    dliNumber: 'O19332928222',
    name: 'OCAD University',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 23000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'artistic campus',
    programs: ['Fine Arts', 'Design', 'Digital Media', 'Illustration'],
  },
  {
    dliNumber: 'O19396019447',
    name: 'Lakehead University',
    province: 'ON',
    city: 'Thunder Bay',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 20000,
    tuitionHigh: 25000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'lakeside campus',
    programs: ['Engineering', 'Environmental Studies', 'Business', 'Education'],
  },
  {
    dliNumber: 'O19147986001',
    name: 'Algonquin College',
    province: 'ON',
    city: 'Ottawa',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'campus by the Rideau Canal',
    programs: ['Business', 'Engineering Technology', 'Health Sciences', 'Digital Media'],
  },
  {
    dliNumber: 'O19147986002',
    name: 'Cambrian College',
    province: 'ON',
    city: 'Sudbury',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 17000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'science & tech focus',
    programs: ['Biomedical Engineering', 'Mining', 'Culinary'],
  },
  {
    dliNumber: 'O19147986003',
    name: 'Canadore College',
    province: 'ON',
    city: 'North Bay',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'broad-program campus',
    programs: ['Forestry', 'Business', 'Nursing'],
  },
  {
    dliNumber: 'O19147986004',
    name: 'Centennial College',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Scarborough multi-campus',
    programs: ['Aviation', 'Engineering', 'Media', 'Community Services'],
  },
  {
    dliNumber: 'O19147986005',
    name: 'Conestoga College',
    province: 'ON',
    city: 'Kitchener',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 19000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'tech hub in K-W',
    programs: ['ICT', 'Architecture', 'Health Sciences'],
  },
  {
    dliNumber: 'O19147986006',
    name: 'Confederation College',
    province: 'ON',
    city: 'Thunder Bay',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'northwestern Ontario',
    programs: ['Wilderness Safety', 'Mining Tech', 'Social Work'],
  },
  {
    dliNumber: 'O19147986007',
    name: 'Durham College',
    province: 'ON',
    city: 'Oshawa',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'automotive and tech campus',
    programs: ['Automotive Tech', 'IT', 'Health Sciences'],
  },
  {
    dliNumber: 'O19147986008',
    name: 'Fanshawe College',
    province: 'ON',
    city: 'London',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 18500,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'large central campus',
    programs: ['Nursing', 'Culinary', 'Business', 'Film'],
  },
  {
    dliNumber: 'O19147986009',
    name: 'Fleming College',
    province: 'ON',
    city: 'Peterborough',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 17000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'environmental sciences focus',
    programs: ['Environmental Tech', 'Police Foundations', 'Arts'],
  },
  {
    dliNumber: 'O19147986010',
    name: 'George Brown College',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'downtown Toronto campuses',
    programs: ['Culinary Arts', 'Design', 'Business', 'IT'],
  },
  {
    dliNumber: 'O19147986011',
    name: 'Georgian College',
    province: 'ON',
    city: 'Barrie',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14500,
    tuitionHigh: 17500,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'waterfront campus in Barrie',
    programs: ['Policing', 'Health Studies', 'Business'],
  },
  {
    dliNumber: 'O19147986012',
    name: 'Humber Polytechnic',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'multiple GTA campuses',
    programs: ['Media Studies', 'Aviation', 'Health', 'Business'],
  },
  {
    dliNumber: 'O19147986013',
    name: 'La Cité Collégiale',
    province: 'ON',
    city: 'Ottawa',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 17000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'French-language campus',
    programs: ['Finance', 'Health', 'IT'],
  },
  {
    dliNumber: 'O19147986014',
    name: 'Lambton College',
    province: 'ON',
    city: 'Sarnia',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 16500,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chemical valley region',
    programs: ['Process Engineering', 'Marine Tech', 'Business'],
  },
  {
    dliNumber: 'O19147986015',
    name: 'Loyalist College',
    province: 'ON',
    city: 'Belleville',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 16500,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Bay of Quinte campus',
    programs: ['Police Foundations', 'Graphic Design', 'Tourism'],
  },
  {
    dliNumber: 'O19147986016',
    name: 'Mohawk College',
    province: 'ON',
    city: 'Hamilton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'downtown Hamilton location',
    programs: ['Engineering', 'Health Sciences', 'Business'],
  },
  {
    dliNumber: 'O19147986017',
    name: 'Niagara College',
    province: 'ON',
    city: 'Welland',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14500,
    tuitionHigh: 17500,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'wine country region',
    programs: ['Winemaking', 'Culinary', 'Business'],
  },
  {
    dliNumber: 'O19147986018',
    name: 'Northern College',
    province: 'ON',
    city: 'Timmins',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'northern Ontario reach',
    programs: ['Mining', 'Forestry', 'Health'],
  },
  {
    dliNumber: 'O19147986019',
    name: 'St. Clair College',
    province: 'ON',
    city: 'Windsor',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14500,
    tuitionHigh: 17500,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'border city campus',
    programs: ['Automotive', 'Health', 'Engineering'],
  },
  {
    dliNumber: 'O19147986020',
    name: 'St. Lawrence College',
    province: 'ON',
    city: 'Kingston',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 17000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic Kingston campus',
    programs: ['Police Foundations', 'Game Design', 'Business'],
  },
  {
    dliNumber: 'O19147986021',
    name: 'Sault College',
    province: 'ON',
    city: 'Sault Ste. Marie',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13500,
    tuitionHigh: 16500,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Great Lakes region',
    programs: ['Marine Tech', 'Automation', 'Health'],
  },
  {
    dliNumber: 'O19147986022',
    name: 'Seneca Polytechnic',
    province: 'ON',
    city: 'Toronto',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'advanced learning institute',
    programs: ['IT', 'Business', 'Media', 'Engineering'],
  },
  {
    dliNumber: 'O19147986023',
    name: 'Sheridan College',
    province: 'ON',
    city: 'Oakville',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 19000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'animation & arts leader',
    programs: ['Animation', 'Design', 'Business', 'IT'],
  },
  {
    dliNumber: 'O19147986024',
    name: 'Ontario Tech University (polytechnic)',
    province: 'ON',
    city: 'Oshawa',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 21000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'tech-focused polytechnic',
    programs: ['Computer Science', 'Engineering', 'IT'],
  },
  // British Columbia
  {
    dliNumber: 'O19330231062',
    name: 'University of British Columbia',
    province: 'BC',
    city: 'Vancouver',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 35000,
    tuitionHigh: 50000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'mountain backdrop campus',
    programs: ['Engineering', 'Computer Science', 'Business', 'Life Sciences'],
  },
  {
    dliNumber: 'O18781994282',
    name: 'Simon Fraser University',
    province: 'BC',
    city: 'Burnaby',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 28000,
    tuitionHigh: 37000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'hilltop campus',
    programs: ['Computer Science', 'Business', 'Environmental Science', 'Communication'],
  },
  {
    dliNumber: 'O19280533442',
    name: 'University of Victoria',
    province: 'BC',
    city: 'Victoria',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 26000,
    tuitionHigh: 34000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'garden campus',
    programs: ['Computer Science', 'Law', 'Engineering', 'Social Sciences'],
  },
  {
    dliNumber: 'O19395299610',
    name: 'Thompson Rivers University',
    province: 'BC',
    city: 'Kamloops',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 22000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'desert campus',
    programs: ['Business Administration', 'Tourism Management', 'Computing Science', 'Education'],
  },
  {
    dliNumber: 'O19283889692',
    name: 'University of Northern British Columbia',
    province: 'BC',
    city: 'Prince George',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'forested campus',
    programs: ['Environmental Science', 'Business', 'Nursing', 'Indigenous Studies'],
  },
  {
    dliNumber: 'O19350676872',
    name: 'Kwantlen Polytechnic University',
    province: 'BC',
    city: 'Surrey',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'suburban campus',
    programs: ['Business Management', 'Interior Design', 'Information Technology', 'Nursing'],
  },
  {
    dliNumber: 'O19280078102',
    name: 'Capilano University',
    province: 'BC',
    city: 'North Vancouver',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'scenic campus',
    programs: ['Film Production', 'Business Administration', 'Tourism Management', 'Jazz Studies'],
  },
  {
    dliNumber: 'O19330635812',
    name: 'Royal Roads University',
    province: 'BC',
    city: 'Victoria',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 21000,
    tuitionHigh: 25000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'castle campus',
    programs: ['Business (MBA)', 'Environmental Science', 'Tourism & Hospitality', 'Education'],
  },
  {
    dliNumber: 'O19395299688',
    name: 'Vancouver Island University',
    province: 'BC',
    city: 'Nanaimo',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'harbor campus',
    programs: ['Business', 'Fisheries & Aquaculture', 'Hospitality Management', 'Education'],
  },
  {
    dliNumber: 'O19361259712',
    name: 'Emily Carr University of Art and Design',
    province: 'BC',
    city: 'Vancouver',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 19000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'artistic campus',
    programs: ['Visual Arts', 'Animation', 'Industrial Design', 'Film and Screen Arts'],
  },
  {
    dliNumber: 'O19347055392',
    name: 'Trinity Western University',
    province: 'BC',
    city: 'Langley',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 25000,
    tuitionHigh: 30000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'suburban campus',
    programs: ['Business Administration', 'Biology', 'Education', 'Nursing'],
  },
  {
    dliNumber: 'O19395299642',
    name: 'University of the Fraser Valley',
    province: 'BC',
    city: 'Abbotsford',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'valley campus',
    programs: ['Criminal Justice', 'Business Administration', 'Agriculture', 'Graphic Design'],
  },
  {
    dliNumber: 'O19330128542',
    name: 'British Columbia Institute of Technology (BCIT)',
    province: 'BC',
    city: 'Burnaby',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'polytechnic campus',
    programs: ['Engineering Technology', 'Computer Systems', 'Health Sciences', 'Business'],
  },
  {
    dliNumber: 'O19319074622',
    name: 'Langara College',
    province: 'BC',
    city: 'Vancouver',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 17000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'urban campus',
    programs: ['University Transfer Arts & Science', 'Business Management', 'Nursing', 'Computer Science'],
  },
  {
    dliNumber: 'O19360973702',
    name: 'Douglas College',
    province: 'BC',
    city: 'New Westminster',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 17000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'city campus',
    programs: ['Accounting', 'Nursing', 'Criminal Justice', 'Computer Science'],
  },
  {
    dliNumber: 'O19279717512',
    name: 'Vancouver Community College',
    province: 'BC',
    city: 'Vancouver',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'downtown campus',
    programs: ['Culinary Arts', 'Automotive Trades', 'Hospitality Management', 'Graphic Design'],
  },
  {
    dliNumber: 'O19361235542',
    name: 'Camosun College',
    province: 'BC',
    city: 'Victoria',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13500,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'park-like campus',
    programs: ['Engineering Technology', 'Nursing', 'Business Administration', 'Sport Management'],
  },
  {
    dliNumber: 'O19395299488',
    name: 'Okanagan College',
    province: 'BC',
    city: 'Kelowna',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'valley campus',
    programs: ['Viticulture Technician', 'Business Administration', 'Computer Information Systems', 'Practical Nursing'],
  },
  {
    dliNumber: 'O19360977332',
    name: 'College of New Caledonia',
    province: 'BC',
    city: 'Prince George',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'northern campus',
    programs: ['Nursing', 'Business', 'Early Childhood Education', 'Welding Technician'],
  },
  {
    dliNumber: 'O19377233362',
    name: 'College of the Rockies',
    province: 'BC',
    city: 'Cranbrook',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'mountain campus',
    programs: ['Tourism Management', 'Business', 'Early Childhood Education', 'Fire Services Training'],
  },
  {
    dliNumber: 'O19360990072',
    name: 'Selkirk College',
    province: 'BC',
    city: 'Castlegar',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12500,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'rural campus',
    programs: ['Digital Arts', 'Forestry Technology', 'Nursing', 'Business Administration'],
  },
  {
    dliNumber: 'O19301182602',
    name: 'North Island College',
    province: 'BC',
    city: 'Courtenay',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'coastal campus',
    programs: ['Business Administration', 'Practical Nursing', 'Tourism & Hospitality', 'Electronics Technician'],
  },
  {
    dliNumber: 'O19394941140',
    name: 'Justice Institute of British Columbia',
    province: 'BC',
    city: 'New Westminster',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'professional training campus',
    programs: ['Law Enforcement Studies', 'Firefighter Training', 'Paramedicine', 'Emergency Management'],
  },
  {
    dliNumber: 'O19395299432',
    name: 'Nicola Valley Institute of Technology',
    province: 'BC',
    city: 'Merritt',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 10000,
    tuitionHigh: 12000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'indigenous college campus',
    programs: ['Environmental Resource Technology', 'Business Administration', 'Social Work', 'Office Administration'],
  },
  {
    dliNumber: 'O19395299444',
    name: 'Northern Lights College',
    province: 'BC',
    city: 'Dawson Creek',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'energy sector campus',
    programs: ['Aircraft Maintenance Engineering', 'Trades & Apprenticeships', 'Business Management', 'Health Care Assistant'],
  },
  // Alberta
  {
    dliNumber: 'O19257171832',
    name: 'University of Alberta',
    province: 'AB',
    city: 'Edmonton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 27000,
    tuitionHigh: 40000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic campus',
    programs: ['Engineering', 'Business', 'Medicine', 'Computer Science'],
  },
  {
    dliNumber: 'O18886830282',
    name: 'University of Calgary',
    province: 'AB',
    city: 'Calgary',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 25000,
    tuitionHigh: 37000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'modern campus',
    programs: ['Engineering', 'Business', 'Medicine', 'Environmental Science'],
  },
  {
    dliNumber: 'O18776949622',
    name: 'University of Lethbridge',
    province: 'AB',
    city: 'Lethbridge',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 22000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'coulee-side campus',
    programs: ['Management', 'Education', 'Health Sciences', 'Fine Arts'],
  },
  {
    dliNumber: 'O19092373272',
    name: 'Athabasca University',
    province: 'AB',
    city: 'Athabasca',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'distance learning campus',
    programs: ['Business Management', 'Computer Science', 'Nursing', 'Psychology'],
  },
  {
    dliNumber: 'O19092022262',
    name: 'MacEwan University',
    province: 'AB',
    city: 'Edmonton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 22000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'urban campus',
    programs: ['Nursing', 'Business', 'Fine Arts', 'Science'],
  },
  {
    dliNumber: 'O18761482032',
    name: 'Mount Royal University',
    province: 'AB',
    city: 'Calgary',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 21000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'foothills campus',
    programs: ['Business Administration', 'Nursing', 'Communications', 'Interior Design'],
  },
  {
    dliNumber: 'O18760756062',
    name: 'Alberta University of the Arts',
    province: 'AB',
    city: 'Calgary',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'arts campus',
    programs: ['Visual Communication Design', 'Fine Arts', 'Animation', 'Jewellery & Metals'],
  },
  {
    dliNumber: 'O19073475522',
    name: 'Concordia University of Edmonton',
    province: 'AB',
    city: 'Edmonton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'riverside campus',
    programs: ['Management', 'Information Technology', 'Psychology', 'Environmental Science'],
  },
  {
    dliNumber: 'O19273782872',
    name: "St. Mary's University",
    province: 'AB',
    city: 'Calgary',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'small campus',
    programs: ['Biology', 'Education', 'Liberal Studies', 'Psychology'],
  },
  {
    dliNumber: 'O18713250142',
    name: "The King's University",
    province: 'AB',
    city: 'Edmonton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 17000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'faith-based campus',
    programs: ['Biology', 'Business', 'Chemistry', 'Music'],
  },
  {
    dliNumber: 'O19390898172',
    name: 'Burman University',
    province: 'AB',
    city: 'Lacombe',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'parkland campus',
    programs: ['Religious Studies', 'Biology', 'Business', 'Wellness Management'],
  },
  {
    dliNumber: 'O18713147522',
    name: 'Ambrose University',
    province: 'AB',
    city: 'Calgary',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'small campus',
    programs: ['Business Administration', 'Behavioural Science', 'Education', 'Christian Studies'],
  },
  {
    dliNumber: 'O18761749692',
    name: 'Southern Alberta Institute of Technology (SAIT)',
    province: 'AB',
    city: 'Calgary',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 19000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'polytechnic campus',
    programs: ['Mechanical Engineering Tech', 'Hospitality Management', 'Culinary Arts', 'Information Technology'],
  },
  {
    dliNumber: 'O18713200642',
    name: 'Northern Alberta Institute of Technology (NAIT)',
    province: 'AB',
    city: 'Edmonton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'polytechnic campus',
    programs: ['Computer Engineering Tech', 'Automotive Service Tech', 'Digital Media', 'Business'],
  },
  {
    dliNumber: 'O19273769422',
    name: 'Bow Valley College',
    province: 'AB',
    city: 'Calgary',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'downtown campus',
    programs: ['Healthcare Aide', 'Business Administration', 'Software Development', 'Early Childhood Education'],
  },
  {
    dliNumber: 'O18795996622',
    name: 'NorQuest College',
    province: 'AB',
    city: 'Edmonton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'urban campus',
    programs: ['Practical Nursing', 'Business Administration', 'Community Support Work', 'English Language Training'],
  },
  {
    dliNumber: 'O19391056880',
    name: 'Red Deer Polytechnic',
    province: 'AB',
    city: 'Red Deer',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'central campus',
    programs: ['Business Administration', 'Nursing', 'Engineering Technology', 'Education'],
  },
  {
    dliNumber: 'O19391056756',
    name: 'Lethbridge College',
    province: 'AB',
    city: 'Lethbridge',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'prairie campus',
    programs: ['Environmental Science', 'Digital Communications', 'Nursing', 'Justice Studies'],
  },
  {
    dliNumber: 'O18795445892',
    name: 'Medicine Hat College',
    province: 'AB',
    city: 'Medicine Hat',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'community campus',
    programs: ['Business Administration', 'Visual Communications', 'Nursing', 'Trades & Technology'],
  },
  {
    dliNumber: 'O18777577472',
    name: 'Lakeland College',
    province: 'AB',
    city: 'Vermilion',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'rural campus',
    programs: ['Agricultural Sciences', 'Firefighter Training', 'Business', 'Environmental Sciences'],
  },
  {
    dliNumber: 'O19283886532',
    name: 'Keyano College',
    province: 'AB',
    city: 'Fort McMurray',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'energy sector campus',
    programs: ['Power Engineering', 'Business Administration', 'Nursing', 'Environmental Technology'],
  },
  {
    dliNumber: 'O19391056848',
    name: 'Northern Lakes College',
    province: 'AB',
    city: 'Slave Lake',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 10000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'remote campus',
    programs: ['Practical Nursing', 'Educational Assistant', 'Human Resource Management', 'Electrical Trades'],
  },
  {
    dliNumber: 'O18713227822',
    name: 'Olds College',
    province: 'AB',
    city: 'Olds',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'agricultural campus',
    programs: ['Agribusiness', 'Horticulture', 'Fashion Marketing', 'Land & Water Resources'],
  },
  {
    dliNumber: 'O111010246767',
    name: 'Portage College',
    province: 'AB',
    city: 'Lac La Biche',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 10000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'northern campus',
    programs: ['Culinary Arts', 'Natural Resources Technology', 'Business Administration', 'Practical Nursing'],
  },
  {
    dliNumber: 'O19391056654',
    name: 'Northwestern Polytechnic (Grande Prairie)',
    province: 'AB',
    city: 'Grande Prairie',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'northern campus',
    programs: ['Business Administration', 'Computing Technology', 'Nursing', 'Kinesiology'],
  },
  // Quebec
  {
    dliNumber: 'O19359212132',
    name: 'McGill University',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 25000,
    tuitionHigh: 50000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic downtown campus',
    programs: ['Engineering', 'Medicine', 'Computer Science', 'Arts'],
  },
  {
    dliNumber: 'O19359211052',
    name: 'Concordia University',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 22000,
    tuitionHigh: 28000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'modern urban campus',
    programs: ['Fine Arts', 'Business', 'Computer Science', 'Engineering'],
  },
  {
    dliNumber: 'O19338281652',
    name: 'Université de Montréal',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 20000,
    tuitionHigh: 25000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'hillside campus',
    programs: ['Law', 'Medicine', 'Pharmacy', 'Architecture'],
  },
  {
    dliNumber: 'O19338281642',
    name: 'Université Laval',
    province: 'QC',
    city: 'Quebec City',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 20000,
    tuitionHigh: 25000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic campus',
    programs: ['Forestry', 'Medicine', 'Law', 'Business Administration'],
  },
  {
    dliNumber: 'O19359211322',
    name: 'HEC Montréal',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 28000,
    tuitionHigh: 35000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'business school campus',
    programs: ['Business Administration (BBA)', 'MBA', 'Finance', 'Marketing'],
  },
  {
    dliNumber: 'O19338281612',
    name: 'Polytechnique Montréal',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 26000,
    tuitionHigh: 30000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'engineering campus',
    programs: ['Mechanical Engineering', 'Computer Engineering', 'Civil Engineering', 'Chemical Engineering'],
  },
  {
    dliNumber: 'O19338281782',
    name: "Bishop's University",
    province: 'QC',
    city: 'Sherbrooke',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 22000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'small town campus',
    programs: ['Business', 'Education', 'Psychology', 'Biology'],
  },
  {
    dliNumber: 'O19359211232',
    name: 'Université de Sherbrooke',
    province: 'QC',
    city: 'Sherbrooke',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 19000,
    tuitionHigh: 24000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'campus in nature',
    programs: ['Medicine', 'Law', 'Engineering', 'Education'],
  },
  {
    dliNumber: 'O19359211342',
    name: 'Université du Québec à Montréal (UQAM)',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 21000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'urban arts campus',
    programs: ['Communications', 'Fine Arts', 'Political Science', 'Management'],
  },
  {
    dliNumber: 'O19338281682',
    name: 'Dawson College',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 8000,
    tuitionHigh: 11000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'english college campus',
    programs: ['Computer Science Technology', 'Social Science', 'Business Administration', 'Graphic Design'],
  },
  {
    dliNumber: 'O19359211082',
    name: 'Vanier College',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 8000,
    tuitionHigh: 11000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'suburban college campus',
    programs: ['Nursing', 'Computer Science Technology', 'Music', 'Business Administration'],
  },
  {
    dliNumber: 'O19359211132',
    name: 'John Abbott College',
    province: 'QC',
    city: 'Sainte-Anne-de-Bellevue',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 7000,
    tuitionHigh: 10000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'lakeside college campus',
    programs: ['Police Technology', 'Professional Theatre', 'Nursing', 'Computer Science'],
  },
  {
    dliNumber: 'O19359211022',
    name: 'Cégep de la Gaspésie et des Îles',
    province: 'QC',
    city: 'Gaspé',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 7000,
    tuitionHigh: 10000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'coastal college campus',
    programs: ['Adventure Tourism', 'Aquaculture', 'Nursing', 'Accounting'],
  },
  {
    dliNumber: 'O19359211202',
    name: 'LaSalle College',
    province: 'QC',
    city: 'Montreal',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'fashion campus',
    programs: ['Fashion Design', 'Hotel Management', 'Graphic Design', 'Game Design'],
  },
  // Manitoba
  {
    dliNumber: 'O19091528512',
    name: 'University of Manitoba',
    province: 'MB',
    city: 'Winnipeg',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'campus by the Red River',
    programs: ['Engineering', 'Agricultural Sciences', 'Business', 'Medicine'],
  },
  {
    dliNumber: 'O19147986012',
    name: 'University of Winnipeg',
    province: 'MB',
    city: 'Winnipeg',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'downtown campus',
    programs: ['Data Science', 'Business Economics', 'Theatre and Film', 'Physics'],
  },
  {
    dliNumber: 'O19201298932',
    name: 'Brandon University',
    province: 'MB',
    city: 'Brandon',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'prairie campus',
    programs: ['Music', 'Environmental Science', 'Education', 'Psychology'],
  },
  {
    dliNumber: 'O19126670302',
    name: 'Université de Saint-Boniface',
    province: 'MB',
    city: 'Winnipeg',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 9000,
    tuitionHigh: 11000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic francophone campus',
    programs: ['Nursing', 'Business Administration', 'Education', 'International Studies'],
  },
  {
    dliNumber: 'O19283880122',
    name: 'University College of the North',
    province: 'MB',
    city: 'The Pas',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 8000,
    tuitionHigh: 10000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'northern campus',
    programs: ['Business Administration', 'Nursing', 'Education', 'Natural Resources Management'],
  },
  {
    dliNumber: 'O19021102272',
    name: 'Canadian Mennonite University',
    province: 'MB',
    city: 'Winnipeg',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 10000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'faith-based campus',
    programs: ['Music', 'Biblical Studies', 'Environmental Studies', 'Business'],
  },
  {
    dliNumber: 'O19147992362',
    name: 'Booth University College',
    province: 'MB',
    city: 'Winnipeg',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'urban campus',
    programs: ['Social Work', 'Psychology', 'Business Administration', 'Theology'],
  },
  {
    dliNumber: 'O19021124362',
    name: 'Providence University College',
    province: 'MB',
    city: 'Otterburne',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'rural campus',
    programs: ['Business Administration', 'Communications', 'Biblical Studies', 'Aviation Management'],
  },
  {
    dliNumber: 'O19395083444',
    name: 'Red River College Polytechnic',
    province: 'MB',
    city: 'Winnipeg',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'polytechnic campus',
    programs: ['Business Technology', 'Hospitality', 'Civil Engineering Tech', 'Nursing'],
  },
  {
    dliNumber: 'O19201282282',
    name: 'Assiniboine Community College',
    province: 'MB',
    city: 'Brandon',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'prairie campus',
    programs: ['Agribusiness', 'Culinary Arts', 'Practical Nursing', 'Civil Technology'],
  },
  {
    dliNumber: 'O19391828428',
    name: 'Manitoba Institute of Trades and Technology (MITT)',
    province: 'MB',
    city: 'Winnipeg',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'technical campus',
    programs: ['Network Technician', 'Business Administration', 'Industrial Welding', 'Cyber Defence'],
  },
  // Saskatchewan
  {
    dliNumber: 'O19425660421',
    name: 'University of Saskatchewan',
    province: 'SK',
    city: 'Saskatoon',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 20000,
    tuitionHigh: 25000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'campus by the river',
    programs: ['Agriculture & Bioresources', 'Engineering', 'Medicine', 'Computer Science'],
  },
  {
    dliNumber: 'O19425660270',
    name: 'University of Regina',
    province: 'SK',
    city: 'Regina',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 22000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'prairie campus',
    programs: ['Business Administration', 'Engineering', 'Media, Art & Performance', 'Nursing'],
  },
  {
    dliNumber: 'O19425521849',
    name: 'Saskatchewan Polytechnic',
    province: 'SK',
    city: 'Saskatoon',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'polytechnic campus',
    programs: ['Practical Nursing', 'Welding Engineering Tech', 'Business', 'Computer Networking'],
  },
  {
    dliNumber: 'O19425193620',
    name: 'Briercrest College and Seminary',
    province: 'SK',
    city: 'Caronport',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 9000,
    tuitionHigh: 12000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'faith-based campus',
    programs: ['Theology', 'Business Administration', 'Psychology', 'Music'],
  },
  {
    dliNumber: 'O214383061827',
    name: 'Great Plains College',
    province: 'SK',
    city: 'Swift Current',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 8000,
    tuitionHigh: 11000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'regional campus',
    programs: ['Welding', 'Business (certificate)', 'Power Engineering', 'Practical Nursing'],
  },
  {
    dliNumber: 'O19425521569',
    name: 'Suncrest College',
    province: 'SK',
    city: 'Yorkton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 8000,
    tuitionHigh: 10000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'regional campus',
    programs: ['Office Administration', 'Early Childhood Education', 'Practical Nursing', 'Business'],
  },
  {
    dliNumber: 'O265527598312',
    name: 'North West College',
    province: 'SK',
    city: 'North Battleford',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 7000,
    tuitionHigh: 10000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'regional campus',
    programs: ['Office Administration', 'Primary Care Paramedic', 'Welding', 'Educational Assistant'],
  },
  {
    dliNumber: 'O145024872092',
    name: 'Southeast College',
    province: 'SK',
    city: 'Weyburn',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 7000,
    tuitionHigh: 10000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'regional campus',
    programs: ['Business (certificate)', 'Hairstylist', 'Practical Nursing', 'Electrician'],
  },
  {
    dliNumber: 'O165662884902',
    name: 'Carlton Trail College',
    province: 'SK',
    city: 'Humboldt',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 7000,
    tuitionHigh: 10000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'regional campus',
    programs: ['Heavy Equipment Operator', 'Continuing Care Assistant', 'Electrician', 'Administration'],
  },
  // Nova Scotia
  {
    dliNumber: 'O19209939282',
    name: 'Dalhousie University',
    province: 'NS',
    city: 'Halifax',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 21000,
    tuitionHigh: 32000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic oceanside campus',
    programs: ['Medicine', 'Engineering', 'Computer Science', 'Law'],
  },
  {
    dliNumber: 'O19021279692',
    name: "Saint Mary's University",
    province: 'NS',
    city: 'Halifax',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 22000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'urban campus',
    programs: ['Business (Finance)', 'Astrophysics', 'Criminology', 'International Development'],
  },
  {
    dliNumber: 'O19391556792',
    name: 'Acadia University',
    province: 'NS',
    city: 'Wolfville',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 19000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'small-town campus',
    programs: ['Biology', 'Environmental Science', 'Business Administration', 'Psychology'],
  },
  {
    dliNumber: 'O19391556899',
    name: 'St. Francis Xavier University',
    province: 'NS',
    city: 'Antigonish',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'collegiate campus',
    programs: ['Business', 'Human Kinetics', 'Nursing', 'Arts & Science'],
  },
  {
    dliNumber: 'O19391556824',
    name: 'Cape Breton University',
    province: 'NS',
    city: 'Sydney',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 17000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'island campus',
    programs: ['Hospitality & Tourism', 'Petroleum Engineering Tech', 'Business', 'Public Health'],
  },
  {
    dliNumber: 'O19301947442',
    name: 'Mount Saint Vincent University',
    province: 'NS',
    city: 'Halifax',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'harbor-view campus',
    programs: ['Public Relations', 'Nutrition', 'Education', 'Business Administration'],
  },
  {
    dliNumber: 'O19021269652',
    name: 'NSCAD University',
    province: 'NS',
    city: 'Halifax',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'art and design campus',
    programs: ['Fine Arts', 'Film', 'Photography', 'Design'],
  },
  {
    dliNumber: 'O19391556726',
    name: 'Université Sainte-Anne',
    province: 'NS',
    city: 'Church Point',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 9000,
    tuitionHigh: 12000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'french seaside campus',
    programs: ['French Studies', 'Business Administration', 'Nursing', 'Education'],
  },
  {
    dliNumber: 'O19391556768',
    name: "University of King's College",
    province: 'NS',
    city: 'Halifax',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 18000,
    tuitionHigh: 20000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic campus',
    programs: ['Journalism', 'Contemporary Studies', 'English', 'History'],
  },
  {
    dliNumber: 'O19091820452',
    name: 'Nova Scotia Community College (NSCC)',
    province: 'NS',
    city: 'Halifax',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'coastal campus',
    programs: ['Marine Engineering Tech', 'Information Technology', 'Culinary Arts', 'Practical Nursing'],
  },
  // New Brunswick
  {
    dliNumber: 'O19348802512',
    name: 'University of New Brunswick',
    province: 'NB',
    city: 'Fredericton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 16000,
    tuitionHigh: 18000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'historic campus',
    programs: ['Computer Science', 'Forestry', 'Business Administration', 'Engineering'],
  },
  {
    dliNumber: 'O19391556532',
    name: 'Université de Moncton',
    province: 'NB',
    city: 'Moncton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 10000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'french-language campus',
    programs: ['Business Administration', 'Nursing', 'Engineering', 'Education'],
  },
  {
    dliNumber: 'O19273922302',
    name: 'Mount Allison University',
    province: 'NB',
    city: 'Sackville',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 19000,
    tuitionHigh: 21000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'small liberal arts campus',
    programs: ['Biology', 'Fine Arts', 'Commerce', 'History'],
  },
  {
    dliNumber: 'O19391556376',
    name: 'St. Thomas University',
    province: 'NB',
    city: 'Fredericton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 15000,
    tuitionHigh: 17000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'liberal arts campus',
    programs: ['Criminology', 'Journalism', 'Human Rights', 'Psychology'],
  },
  {
    dliNumber: 'O19391556439',
    name: 'New Brunswick Community College (NBCC)',
    province: 'NB',
    city: 'Fredericton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 8000,
    tuitionHigh: 11000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'provincial college campus',
    programs: ['Business Administration', 'Information Technology', 'Electrical Engineering Tech', 'Practical Nursing'],
  },
  {
    dliNumber: 'O19391556654',
    name: 'Collège communautaire du Nouveau-Brunswick (CCNB)',
    province: 'NB',
    city: 'Bathurst',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 7000,
    tuitionHigh: 10000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'francophone college campus',
    programs: ['Welding Technology', 'Civil Engineering Tech', 'Business Administration', 'Nursing'],
  },
  {
    dliNumber: 'O19391556333',
    name: 'NB College of Craft and Design',
    province: 'NB',
    city: 'Fredericton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 7000,
    tuitionHigh: 9000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'arts college campus',
    programs: ['Graphic Design', 'Aboriginal Visual Arts', 'Photography', 'Fashion Design'],
  },
  {
    dliNumber: 'O19391275763',
    name: 'Crandall University',
    province: 'NB',
    city: 'Moncton',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 14000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'faith-based campus',
    programs: ['Business Administration', 'Biology', 'Education', 'Religious Studies'],
  },
  {
    dliNumber: 'O19348776942',
    name: 'Kingswood University',
    province: 'NB',
    city: 'Sussex',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 9000,
    tuitionHigh: 11000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Christian college campus',
    programs: ['Ministry', 'Christian School Education', 'Biblical Studies', 'Pastoral Theology'],
  },
  // Prince Edward Island
  {
    dliNumber: 'O19220071452',
    name: 'University of Prince Edward Island',
    province: 'PE',
    city: 'Charlottetown',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 13000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'island campus',
    programs: ['Veterinary Medicine', 'Nursing', 'Business Administration', 'Computer Science'],
  },
  {
    dliNumber: 'O19220082122',
    name: 'Holland College',
    province: 'PE',
    city: 'Charlottetown',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 9000,
    tuitionHigh: 12000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'practical training campus',
    programs: ['Culinary Arts', 'Police Science', 'Computer Networking', 'Early Childhood Education'],
  },
  {
    dliNumber: 'O19220114112',
    name: "Collège de l'Île",
    province: 'PE',
    city: 'Wellington',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 6000,
    tuitionHigh: 8000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'french college campus',
    programs: ['Practical Nursing', 'Business Administration', 'Youth Worker', 'Bilingual Administration'],
  },
  // Newfoundland and Labrador
  {
    dliNumber: 'O19440995346',
    name: 'Memorial University of Newfoundland',
    province: 'NL',
    city: "St. John's",
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'ocean-side campus',
    programs: ['Marine Biology', 'Engineering', 'Earth Sciences', 'Business Administration'],
  },
  {
    dliNumber: 'O19441088976',
    name: 'College of the North Atlantic',
    province: 'NL',
    city: "St. John's",
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 8000,
    tuitionHigh: 10000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'provincial college campus',
    programs: ['Petroleum Engineering Tech', 'Business Management', 'Aircraft Maintenance', 'Web Development'],
  },
  // Yukon
  {
    dliNumber: 'YT110000001',
    name: 'Yukon University',
    province: 'YT',
    city: 'Whitehorse',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Canada’s only northern university',
    programs: ['Northern Studies', 'Business', 'Health', 'First Nations Governance'],
  },
  {
    dliNumber: 'YT110000002',
    name: 'Northern Institute (Yukon UA)',
    province: 'YT',
    city: 'Whitehorse',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'vocational & trades training',
    programs: ['Trades', 'Community Studies'],
  },
  {
    dliNumber: 'YT110000003',
    name: 'EiGHT Aboriginal Training',
    province: 'YT',
    city: 'Whitehorse',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 10000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'First Nations skills training',
    programs: ['Carpentry', 'Business', 'Transport'],
  },
  {
    dliNumber: 'YT110000004',
    name: 'YWCA Yukon Training Centre',
    province: 'YT',
    city: 'Whitehorse',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 9000,
    tuitionHigh: 12000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'women‑focused vocational',
    programs: ['Hospitality', 'Life Skills', 'Trades'],
  },
  {
    dliNumber: 'YT110000005',
    name: 'Lil’wat First Nation Training',
    province: 'YT',
    city: 'Whitehorse',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 10000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Indigenous cultural education',
    programs: ['Indigenous Governance', 'Arts'],
  },
  // Northwest Territories
  {
    dliNumber: 'NT120000001',
    name: 'Aurora College',
    province: 'NT',
    city: 'Yellowknife',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 12000,
    tuitionHigh: 16000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'multiple NWT campuses',
    programs: ['Northern Science', 'Trades', 'Business'],
  },
  {
    dliNumber: 'NT120000002',
    name: 'Science Institute of the North',
    province: 'NT',
    city: 'Yellowknife',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'STEM-focused training',
    programs: ['Environmental Tech', 'Community Safety'],
  },
  {
    dliNumber: 'NT120000003',
    name: 'Indigenous Cultural College NT',
    province: 'NT',
    city: 'Inuvik',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 10000,
    tuitionHigh: 13000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Indigenous culture programs',
    programs: ['Cultural Arts', 'Governance'],
  },
  {
    dliNumber: 'NT120000004',
    name: 'Trades Centre NWT',
    province: 'NT',
    city: 'Yellowknife',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'trades training facility',
    programs: ['Carpentry', 'Electrical', 'Plumbing'],
  },
  {
    dliNumber: 'NT120000005',
    name: 'Aurora Adult Learning Centre',
    province: 'NT',
    city: 'Yellowknife',
    pgwpEligible: false,
    sdsEligible: false,
    tuitionLow: 6000,
    tuitionHigh: 9000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'adult upgrading & literacy',
    programs: ['Adult Basic Ed', 'Workforce Prep'],
  },
  // Nunavut
  {
    dliNumber: 'NU130000001',
    name: 'Nunavut Arctic College',
    province: 'NU',
    city: 'Iqaluit',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'territory-wide campuses',
    programs: ['Inuit Studies', 'Trades', 'Community Justice'],
  },
  {
    dliNumber: 'NU130000002',
    name: 'Nunavut Sivuniksavut (NSI)',
    province: 'NU',
    city: 'Ottawa (HQ)',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 10000,
    tuitionHigh: 14000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Inuit cultural training in Ottawa',
    programs: ['Inuit Governance', 'History', 'Language'],
  },
  {
    dliNumber: 'NU130000003',
    name: 'Kitikmeot Campus (Arctic College)',
    province: 'NU',
    city: 'Cambridge Bay',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Kitikmeot region campus',
    programs: ['Trades', 'Environment', 'IT'],
  },
  {
    dliNumber: 'NU130000004',
    name: 'Kivalliq Campus (Arctic College)',
    province: 'NU',
    city: 'Rankin Inlet',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Kivalliq region campus',
    programs: ['Cultural Studies', 'Health', 'Trades'],
  },
  {
    dliNumber: 'NU130000005',
    name: 'Qikiqtani Campus (Arctic College)',
    province: 'NU',
    city: 'Iqaluit',
    pgwpEligible: true,
    sdsEligible: true,
    tuitionLow: 11000,
    tuitionHigh: 15000,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'Qikiqtani region',
    programs: ['Language Revitalization', 'Trades', 'Community Health'],
  },
];
